Add pt-BR i18n support
nhn/tui.editor pull request #1220
Opened 2020-10-08 18:27 UTC by nicolashuber

### Please check if the PR fulfills these requirements
- [ ] It's the right issue type on the title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description
Add brazilian portuguese support.

2020-10-14 03:10 UTC, seonim-ryu requested changes
@nicolashuber Thank you for your contributing. If you update the commit and PR title according to our convention, this PR will be merged. Below is an example.

> Convention for other PR : https://github.com/nhn/tui.editor/pull/1162

2020-10-15 12:09 UTC, nicolashuber commented
@seonim-ryu  Done!

2020-10-19 02:02 UTC, seonim-ryu commented on apps/editor/src/js/i18n/pt-br.js
> +Editor.setLanguage('pt', 'pt-BR', {
@nicolashuber Oops... I did a build test on a local PC, but Portuguese wasn't set, so I checked again and the parameter type was wrong.

The ʻEditor.setLanguage` function can only take 2 parameters, and the first parameter must be a string or an array type. Check out the guide below.

> https://github.com/nhn/tui.editor/blob/master/apps/editor/docs/i18n.md#contributing

2020-10-21 01:05 UTC, seonim-ryu approved these changes

2020-10-21 01:05 UTC, merged