fix: focus with colorsyntax on multi instances (fix #2413)
nhn/tui.editor pull request #2441
Opened 2022-04-12 08:46 UTC by jajugoguma

### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has a description of the breaking change

### Description

* Fixed that set focus to the first editor when using the color syntax plugin in multi-instance.
  * Changed to find the editing area element in the parent element (Editor Container element) of the dropdown element of the current color syntax plugin.
  * The process of finding an edit area element has been changed to before moving focus into the editor, rather than when the editor has focus set.

**As-Is**
![](https://user-images.githubusercontent.com/41339744/162920092-d33602aa-f3bf-458d-8c15-ef5334c3c38b.gif)

**To-Be**
![](https://user-images.githubusercontent.com/41339744/162920134-c0d5b736-13af-477c-8f8a-1727086ac099.gif)

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-04-13 05:51 UTC, adhrinae requested changes
리뷰 완료합니다. 테스트 부분 확인해주시고요.
그리고 다른 플러그인에도 이번 이슈랑 비슷한 경우가 일어날 일은 없나요?
여러 인스턴스를 만들어놓고 플러그인을 사용할 때 현재 포커스중인 에디터를 더 쉽게 찾을 수 있는 방법을 기본적으로 마련하는게 좋겠는데요.

2022-04-13 05:51 UTC, adhrinae commented on plugins/color-syntax/src/__test__/integration/colorSyntaxPlugin.spec.ts
> +    it.only('should focus to correct editor when using color syntax plugin', () => {
또 `only` 안빠졌어요.

2022-04-13 05:51 UTC, adhrinae commented on plugins/color-syntax/src/__test__/integration/colorSyntaxPlugin.spec.ts
> +      );
혹시 `container2.contains(document.activeElement)` 로는 안되나요?

https://developer.mozilla.org/en-US/docs/Web/API/Node/contains

2022-04-13 08:21 UTC, jajugoguma commented on plugins/color-syntax/src/__test__/integration/colorSyntaxPlugin.spec.ts
> +      );
현재 `activeElement`가 정확히 에디터 내 에디팅 요소인지 확인하는게 명확하다고 판단했습니다.

2022-04-13 08:23 UTC, adhrinae commented on plugins/color-syntax/src/__test__/integration/colorSyntaxPlugin.spec.ts
> +      );
네 그런데 저 쿼리 셀렉터는 다분히 구현 의존적인데 비해
"`document.activeElement` 가 어쨌든 `container2` 안에 있는거냐" 를 확인하기 위해 `contains` 를 쓰는게 어떻겠냐는 의미여요.

2022-04-13 09:54 UTC, jajugoguma commented on plugins/color-syntax/src/__test__/integration/colorSyntaxPlugin.spec.ts
> +      );
구현 의존적이라는데 동감하기 때문에 말씀하신 것처럼 요소를 포함하는지 검증하도록 변경했습니다.

2022-04-13 12:04 UTC, adhrinae approved these changes

2022-04-14 00:47 UTC, jwlee1108 approved these changes
리뷰 완료합니다.

2022-04-14 01:38 UTC, merged